- project:
    templates:
      - openstack-python3-xena-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - rbd-iscsi-client-code-coverage:
            voting: false

- job:
    name: rbd-iscsi-client-code-coverage
    parent: openstack-tox-cover
    timeout: 2400
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^rbd_iscsi_client/locale/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
